install-nix:
    curl --proto '=https' --tlsv1.2 -L https://nixos.org/nix/install | sh -s -- --no-daemon

install-rustup:
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh 

install-rust:
    . .cargo/env && rustup default stable && rustup component add rust-analyzer

install-fnm:
    . .cargo/env && cargo install fnm

install-node:
    . .cargo/env && fnm install --lts

home-manager-switch:
    . .nix-profile/etc/profile.d/nix.sh && nix run home-manager switch

clean:
    . .nix-profile/etc/profile.d/nix.sh && nix-store --gc

install-pnpm:
    npm i -g pnpm

install-opencode:
    npm i -g opencode-ai
